apiVersion: v1
kind: Service
metadata:
  name: example
  namespace: nginx-example
  labels:
    app: example
spec:
  ports:
    - name: http
      targetPort: 8080
      port: 8080
  selector:
    app: example
