apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: backend
  name: backend
  labels:
    name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      name: backend
  template:
    metadata:
      labels:
        name: backend
    spec:
      containers:
        - name: backend
          image: backend:latest
          imagePullPolicy: Never # since we are using a local image in minikube
          resources:
            limits:
              cpu: "0.5"
              memory: "500Mi"
            requests:
              cpu: "0.25"
              memory: "50Mi"
          ports:
            - containerPort: 5000
          env:
            - name: ENVIRONMENT_CONTEXT
              value: "kube"
