version: '3.9'

services:
  flask:
    container_name: flask
    restart: always
    build: src/flask
    ports:
      - "5000:5000"
    environment:
      - ENVIRONMENT=docker-compose

  nginx:
    container_name: nginx
    restart: always
    build: src/nginx
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=docker-compose
    depends_on:
      - flask
