apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: frontend
  labels:
    name: frontend
spec:
  ports:
    - name: http
      targetPort: 8080
      port: 8080
  selector:
    name: frontend
